//
// Created by RGAA on 26/02/2025.
//

#ifndef GAMMARAYSERVER_MGR_DEVICE_H
#define GAMMARAYSERVER_MGR_DEVICE_H

#include <string>

namespace tc
{
    class MgrDevice {
    public:
        int id_{};
        // 9 numbers
        std::string device_id_;
        // user id
        std::string belong_to_user_;
        // generated by
        std::string seed_;
        // random password
        std::string random_pwd_;
        // safety password
        std::string safety_pwd_;
        // 0 -> alive
        // 1 -> deleted
        int deleted_{0};

        int64_t created_timestamp_{0};
    };

}

#endif //GAMMARAYSERVER_MGR_DEVICE_H
